name: Container

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  container:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: docker build -t ${{ env.IMAGE_NAME }} .

      - run: docker run -p 8000:8000 --name ${{ env.IMAGE_NAME }} -d ${{ env.IMAGE_NAME }}
        timeout-minutes: 3

      - name: Run the health check validation
        run: while ! curl -s 'http://localhost:8000/health' | grep '"status":"ok"'; do sleep 1; done
        timeout-minutes: 3

      - name: Get the container logs
        run: docker logs --details ${{ env.IMAGE_NAME }}
        if: always()
